function createfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, X9, Y9, X10, Y10, X11, Y11, X12, Y12, X13, Y13, X14, Y14, X15, Y15, X16, Y16, X17, Y17, X18, Y18, X19, Y19, X20, Y20, X21, Y21, X22, Y22, X23, Y23, X24, Y24, X25, Y25, X26, Y26, X27, Y27, X28, Y28, X29, Y29, X30, Y30, X31, Y31, X32, Y32, X33, Y33, X34, Y34, X35, Y35, X36, Y36, X37, Y37, X38, Y38, X39, Y39, X40, Y40, X41, Y41, X42, Y42, X43, Y43, X44, Y44, X45, Y45, X46, Y46, X47, Y47, X48, Y48, XData1, YData1, XData2, YData2)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7, X8, Y8, X9, Y9, X10, Y10, X11, Y11, X12, Y12, X13, Y13, X14, Y14, X15, Y15, X16, Y16, X17, Y17, X18, Y18, X19, Y19, X20, Y20, X21, Y21, X22, Y22, X23, Y23, X24, Y24, X25, Y25, X26, Y26, X27, Y27, X28, Y28, X29, Y29, X30, Y30, X31, Y31, X32, Y32, X33, Y33, X34, Y34, X35, Y35, X36, Y36, X37, Y37, X38, Y38, X39, Y39, X40, Y40, X41, Y41, X42, Y42, X43, Y43, X44, Y44, X45, Y45, X46, Y46, X47, Y47, X48, Y48, XDATA1, YDATA1, XDATA2, YDATA2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  vector of x data
%  Y6:  vector of y data
%  X7:  vector of x data
%  Y7:  vector of y data
%  X8:  vector of x data
%  Y8:  vector of y data
%  X9:  vector of x data
%  Y9:  vector of y data
%  X10:  vector of x data
%  Y10:  vector of y data
%  X11:  vector of x data
%  Y11:  vector of y data
%  X12:  vector of x data
%  Y12:  vector of y data
%  X13:  vector of x data
%  Y13:  vector of y data
%  X14:  vector of x data
%  Y14:  vector of y data
%  X15:  vector of x data
%  Y15:  vector of y data
%  X16:  vector of x data
%  Y16:  vector of y data
%  X17:  vector of x data
%  Y17:  vector of y data
%  X18:  vector of x data
%  Y18:  vector of y data
%  X19:  vector of x data
%  Y19:  vector of y data
%  X20:  vector of x data
%  Y20:  vector of y data
%  X21:  vector of x data
%  Y21:  vector of y data
%  X22:  vector of x data
%  Y22:  vector of y data
%  X23:  vector of x data
%  Y23:  vector of y data
%  X24:  vector of x data
%  Y24:  vector of y data
%  X25:  vector of x data
%  Y25:  vector of y data
%  X26:  vector of x data
%  Y26:  vector of y data
%  X27:  vector of x data
%  Y27:  vector of y data
%  X28:  vector of x data
%  Y28:  vector of y data
%  X29:  vector of x data
%  Y29:  vector of y data
%  X30:  vector of x data
%  Y30:  vector of y data
%  X31:  vector of x data
%  Y31:  vector of y data
%  X32:  vector of x data
%  Y32:  vector of y data
%  X33:  vector of x data
%  Y33:  vector of y data
%  X34:  vector of x data
%  Y34:  vector of y data
%  X35:  vector of x data
%  Y35:  vector of y data
%  X36:  vector of x data
%  Y36:  vector of y data
%  X37:  vector of x data
%  Y37:  vector of y data
%  X38:  vector of x data
%  Y38:  vector of y data
%  X39:  vector of x data
%  Y39:  vector of y data
%  X40:  vector of x data
%  Y40:  vector of y data
%  X41:  vector of x data
%  Y41:  vector of y data
%  X42:  vector of x data
%  Y42:  vector of y data
%  X43:  vector of x data
%  Y43:  vector of y data
%  X44:  vector of x data
%  Y44:  vector of y data
%  X45:  vector of x data
%  Y45:  vector of y data
%  X46:  vector of x data
%  Y46:  vector of y data
%  X47:  vector of x data
%  Y47:  vector of y data
%  X48:  vector of x data
%  Y48:  vector of y data
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata

%  Auto-generated by MATLAB on 04-Apr-2019 18:40:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X2,Y2,'Color',[1 0 0]);

% Create plot
plot(X3,Y3,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X4,Y4,'Color',[1 0 0]);

% Create plot
plot(X5,Y5,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X6,Y6,'Color',[1 0 0]);

% Create plot
plot(X7,Y7,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X8,Y8,'Color',[1 0 0]);

% Create plot
plot(X9,Y9,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X10,Y10,'Color',[1 0 0]);

% Create plot
plot(X11,Y11,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X12,Y12,'Color',[1 0 0]);

% Create plot
plot(X13,Y13,'Color',[0 0 0]);

% Create plot
plot(X14,Y14,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X2,Y2,'Color',[1 0 0]);

% Create plot
plot(X15,Y15,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X4,Y4,'Color',[1 0 0]);

% Create plot
plot(X16,Y16,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X6,Y6,'Color',[1 0 0]);

% Create plot
plot(X17,Y17,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X8,Y8,'Color',[1 0 0]);

% Create plot
plot(X18,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X10,Y10,'Color',[1 0 0]);

% Create plot
plot(X19,Y19,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X12,Y12,'Color',[1 0 0]);

% Create plot
plot(X20,Y20,'Color',[0 0 0]);

% Create plot
plot(X21,Y21,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X2,Y2,'Color',[1 0 0]);

% Create plot
plot(X22,Y22,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X4,Y4,'Color',[1 0 0]);

% Create plot
plot(X23,Y23,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X6,Y6,'Color',[1 0 0]);

% Create plot
plot(X24,Y24,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X8,Y8,'Color',[1 0 0]);

% Create plot
plot(X25,Y25,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X10,Y10,'Color',[1 0 0]);

% Create plot
plot(X26,Y26,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X12,Y12,'Color',[1 0 0]);

% Create plot
plot(X27,Y27,'Color',[0 0 0]);

% Create plot
plot(X28,Y28,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X2,Y2,'Color',[1 0 0]);

% Create plot
plot(X29,Y29,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X4,Y4,'Color',[1 0 0]);

% Create plot
plot(X30,Y30,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X6,Y6,'Color',[1 0 0]);

% Create plot
plot(X31,Y31,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X8,Y8,'Color',[1 0 0]);

% Create plot
plot(X32,Y32,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X10,Y10,'Color',[1 0 0]);

% Create plot
plot(X33,Y33,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X12,Y12,'Color',[1 0 0]);

% Create plot
plot(X34,Y34,'Color',[0 0 0]);

% Create plot
plot(X35,Y35,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X2,Y2,'Color',[1 0 0]);

% Create plot
plot(X36,Y36,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X4,Y4,'Color',[1 0 0]);

% Create plot
plot(X37,Y37,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X6,Y6,'Color',[1 0 0]);

% Create plot
plot(X38,Y38,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X8,Y8,'Color',[1 0 0]);

% Create plot
plot(X39,Y39,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X10,Y10,'Color',[1 0 0]);

% Create plot
plot(X40,Y40,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X12,Y12,'Color',[1 0 0]);

% Create plot
plot(X41,Y41,'Color',[0 0 0]);

% Create plot
plot(X42,Y42,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X2,Y2,'Color',[1 0 0]);

% Create plot
plot(X43,Y43,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X4,Y4,'Color',[1 0 0]);

% Create plot
plot(X44,Y44,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X6,Y6,'Color',[1 0 0]);

% Create plot
plot(X45,Y45,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X8,Y8,'Color',[1 0 0]);

% Create plot
plot(X46,Y46,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X10,Y10,'Color',[1 0 0]);

% Create plot
plot(X47,Y47,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X12,Y12,'Color',[1 0 0]);

% Create plot
plot(X48,Y48,'Color',[0 0 0]);

% Create line
line(XData1,YData1,'Parent',axes1);

% Create line
line(XData2,YData2,'Parent',axes1);

% Create xlabel
xlabel('F/m0 [N/(kg/s)]');

% Create ylabel
ylabel('S [(g/s)/kN]');

box(axes1,'on');
% Create textarrow
annotation(figure1,'textarrow',[0.547494780793319 0.474425887265135],...
    [0.346192224622028 0.497300215982718],'String',{'alpha = 8'});

% Create textarrow
annotation(figure1,'textarrow',[0.690501043841336 0.617432150313152],...
    [0.444464362850969 0.595572354211659],'String',{'alpha = 6'});

% Create textarrow
annotation(figure1,'textarrow',[0.451983298538622 0.378914405010438],...
    [0.268978401727861 0.420086393088552],'String',{'alpha = 10'});

% Create textarrow
annotation(figure1,'textarrow',[0.729645093945719 0.695198329853861],...
    [0.571354211663063 0.638228941684661],'String',{'Pi C = 40'});

% Create textarrow
annotation(figure1,'textarrow',[0.660751565762004 0.706680584551148],...
    [0.839172786177106 0.782937365010799],'String',{'Pi C = 20'});

% Create arrow
annotation(figure1,'arrow',[0.868475991649269 0.866388308977035],...
    [0.68582505399568 0.538876889848812]);

% Create arrow
annotation(figure1,'arrow',[0.351774530271399 0.468684759916493],...
    [0.146948164146868 0.14902807775378]);

% Create textbox
annotation(figure1,'textbox',...
    [0.477035490605427 0.133989200297493 0.10334029442831 0.0372570200048822],...
    'String',{'Min F/m0'});

% Create textbox
annotation(figure1,'textbox',...
    [0.822025052192063 0.498460042630101 0.0704592901878944 0.0372570200048821],...
    'String',{'Max S'},...
    'FitBoxToText','off');

